# Generated by Django 6.0.3 on 2026-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resident_user_alter_administrator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='name',
        ),
        migrations.AlterField(
            model_name='resident',
            name='department',
            field=models.CharField(max_length=10, verbose_name='Número de departamento'),
        ),
    ]
