# Generated by Django 6.0.3 on 2026-04-07 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la zona')),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad máxima')),
                ('image', models.ImageField(upload_to='zone_images/')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espacio común',
                'verbose_name_plural': 'Espacios comunes',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del evento')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
