# Generated by Django 6.0.3 on 2026-04-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='image',
        ),
    ]
