# Generated by Django 6.0.3 on 2026-04-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_remove_zone_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='available',
            new_name='is_available',
        ),
    ]
