# Generated by Django 6.0.3 on 2026-04-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['event_date'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_picture',
            field=models.ImageField(blank=True, null=True, upload_to='zone_pictures/'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
