# Generated by Django 6.0.3 on 2026-05-05 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_alter_booking_options_zone_zone_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Es recurrente'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='Reserva padre si es una instancia de una recurrencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='zones.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Fecha en la que termina la recurrencia', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.CharField(choices=[('NONE', 'No recurrente'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Cada dos semanas'), ('MONTHLY', 'Mensual')], default='NONE', max_length=20, verbose_name='Patrón de recurrencia'),
        ),
    ]
